version: '3.8'

services:
  transcribe:
    build: .
    container_name: youtube-transcribe-prod
    ports:
      - "8000:8000"
    environment:
      - MODE=api
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID}
      - VERTEX_AI_MODEL=${VERTEX_AI_MODEL:-gemini-2.0-flash}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LANGUAGE_CODE=hu-HU
      - SYNC_SIZE_LIMIT_MB=10
      - MAX_CONCURRENT_JOBS=10
      - LOG_LEVEL=INFO
    volumes:
      - ${SERVICE_ACCOUNT_PATH:-./credentials/service-account.json}:/app/credentials/service-account.json:ro
      - transcribe_data:/app/data
      - transcribe_temp:/app/temp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: youtube-transcribe-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - transcribe
    restart: unless-stopped

volumes:
  transcribe_data:
    driver: local
  transcribe_temp:
    driver: local

networks:
  default:
    name: transcribe-prod-network